---
pipeline:
  name: woohoo
  git:
    owner:       jhunt
    repo:        super-meme
    private_key: (( vault "secret/exodus/snw-jhunt-lab/super-meme/gh:private" ))

  vault:
    url:    https://vault.lab.starkandwayne.com
    verify: no
    role:   (( vault "concourse/main/jhunt-lab/vault:role-id" ))
    secret: (( vault "concourse/main/jhunt-lab/vault:secret-id" ))

  slack:
    webhook: https://www.jameshunt.us
    channel: hahahahahah

  boshes:
    c-e-n-g-a-g-e-1: &bosh
      # FIXME - why is this not just from exodus!?
      url:      (( vault "secret/exodus/snw-jhunt-lab/bosh:url" ))
      ca_cert:  (( vault "secret/exodus/snw-jhunt-lab/bosh:ca_cert" ))
      username: (( vault "secret/exodus/snw-jhunt-lab/bosh:admin_username" ))
      password: (( vault "secret/exodus/snw-jhunt-lab/bosh:admin_password" ))

    c-e-n-g-a-g-e-2: *bosh
    c-e-n-g-a-g-e-m-e-n-t: *bosh

  layouts:
    default: |+
      auto c-*
      c-e-n-g-a-g-e-1 -> c-e-n-g-a-g-e-2
      c-e-n-g-a-g-e-1 -> c-e-n-g-a-g-e-m-e-n-t
